### ISSUE TITLE
Describe what is supported where

### ISSUE THREAD

**Issue by rauschma** [bterlson/es-host-wrapper#2]
In the readme, could you describe which hosts are supported where (Windows vs. OS X vs. Linux)?

* d8, sshell: do I need to install anything?
* ch.exe: looks like this is Windows-online(?)

**Comment by bterlson** [comment]
Yeah I will. I have a blurb about it on bterlson/eshost but could say more.

ch.exe is the chakra console host, you have to build it yourself from source once we OSS. Windows only.
d8.exe is the V8 console host, you have to build it from source. Cross-plat.
jsshell: Mozilla's console host. You can download for your platform here: https://archive.mozilla.org/pub/firefox/nightly/latest-mozilla-central/
JSC has a command line host as well which I'd like to support, but sadly it doesn't run on my platform (see #1).

Hope this helps until I update the readme!

**Comment by bterlson** [comment]
@rauschma The readme should be much more clear now. Check it out!

**Comment by rauschma** [comment]
Awesome. Love the table!
